services:
  tts-cpu:
    build:
      context: ../..
      dockerfile: docker/cpu/Dockerfile
    ports:
      - "8100:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.8'  # 限制CPU使用率为80%
          memory: '16G'  # 限制内存使用为16GB