services:
  tts-gpu:
    build:
      context: ../..
      dockerfile: docker/gpu/Dockerfile
    ports:
      - "8101:5000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    command: python3 app/main.py
    deploy:
      resources:
        limits:
          cpus: '0.8'  # 限制CPU使用率为80%
          memory: '16G'  # 限制内存使用为16GB
        reservations:
          devices:
            - capabilities: [gpu]